version: '3.0'
services:
  travelapp-backend:
    # Building
    container_name: heap-travel-app
    image: soonann/heap-travel-app:latest
    build: .

    # Volumes
    volumes:
      - .:/opt/app

    # Running
    ports: 
      - "8080:8080"

    env_file: ./docker-compose.env