version: '3.0'
services:
  travelapp-db:
  
    container_name: heap-travel-app-db
    image: postgres 
    env_file:
      - ./docker-compose-local.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  travelapp-backend:
 
    container_name: heap-travel-app
    image: soonann/heap-travel-app:latest
    build: .
    env_file: ./docker-compose-production.env
    restart: always
    depends_on:
      - db
    volumes:
      - .:/opt/app
    ports: 
      - "8080:8080"

volumes:
  postgres_data:
