version: '3.0'
services:
  travelapp-db:
    container_name: heap-travel-app-db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./docker-compose.env
    ports:
      - 5432:5432
  travelapp-backend:
    # Building
    container_name: heap-travel-app
    image: soonann/heap-travel-app:latest
    build: .

    # Volumes
    volumes:
      - .:/opt/app

    # Running
    ports: 
      - "8080:8080"

    env_file: ./docker-compose.env
    depends_on:
      - db
    restart: always
 

volumes:
  postgres_data:
